#!/bin/sh
#

[ -r /etc/lsb-release ] && . /etc/lsb-release

printf "\n"
echo "\e[1;34m 
                         __________    _______________
                        \____      /  /      ___      |
                             /    /  /     /    /    /
                            /    /  /     /    /    /
                           /    /  /     /    /    /
                           \___/   \____/     \___/

  __  __   ___   _       _       _____   _   _   _   _   ___   _   _   __  __ 
 |  \/  | |_ _| | |     | |     | ____| | \ | | | \ | | |_ _| | | | | |  \/  |
 | |\/| |  | |  | |     | |     |  _|   |  \| | |  \| |  | |  | | | | | |\/| |
 | |  | |  | |  | |___  | |___  | |___  | |\  | | |\  |  | |  | |_| | | |  | |
 |_|  |_| |___| |_____| |_____| |_____| |_| \_| |_| \_| |___|  \___/  |_|  |_|                                                                       
\e[0m"

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
printf "\n"
printf "Welcome to MILLENNIUM %s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
